baseURL = 'https://fabric8.io/kubernetes-client/'
locale = 'en-us'
title = 'Fabric8 Kubernetes Client'
[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/fabric8io/kubernetes-client'
  BookSearch = true
  BookComments = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = ".."
    target = "content/docs"
    files = [
      'CHEATSHEET.md',
      'CRD-generator.md',
      'CRD-generator-migration-v2.md',
      'FAQ.md',
      'java-generation-from-CRD.md',
      'kube-api-test.md',
      'KubernetesClientWithIPv6Clusters.md',
      'KubernetesLog4j.md',
      'KubernetesOperatorsInJavaWrittenUsingFabric8.md',
      'MIGRATION-v5.md',
      'MIGRATION-v6.md',
      'MIGRATION-v7.md',
    ]

[menu]
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/fabric8io/kubernetes-client"
    weight = 1