#
# Copyright (C) 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'ide-config/**'
      - '**.md'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-build-kubernetes-client-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - java: 11
            os: ubuntu-latest
          - java: 17
            os: ubuntu-latest
          - java: 21
            os: ubuntu-latest
    name: Java ${{ matrix.environment.java }} Maven
    runs-on: ${{ matrix.environment.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set open files (threads) limit
        run: |
          sudo prlimit --pid $$ --nofile=500000:500000
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.environment.java  }}
          distribution: 'temurin'
      - name: Build Project
        #run: make install MAVEN_ARGS="${MAVEN_ARGS}"
        run: mvn ${MAVEN_ARGS} install
      - name: Check java-generator CLI
        run: |
          chmod a+x java-generator/cli/target/java-gen
          java-generator/cli/target/java-gen --source=java-generator/core/src/test/resources/crontab-crd.yml --target=./tmp
